<MainGrid>:

    name: 'Main'

    GridLayout:

        rows: 3

        Label:
            size_hint: 1, 1.338
            text: ""

        BoxLayout:

            size_hint: 1, 1.338

            Button:

            Button:
                text: 'Collect Discography'
                on_release: root.middle_click()

            Button:

        Label:
            size_hint: 1, 1.338
            text: ""